repos:
# Pre-commit hooks for basic checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-yaml
    - id: check-json
    - id: check-toml
    - id: check-xml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-added-large-files
      args: ['--maxkb=1000']
    - id: check-merge-conflict
    - id: debug-statements
    - id: detect-private-key
    - id: check-case-conflict
    - id: check-docstring-first
    - id: mixed-line-ending
      args: ['--fix=lf']

# isort for import sorting
- repo: https://github.com/PyCQA/isort
  rev: 5.13.2
  hooks:
    - id: isort
      args: ["--profile", "black"]

# Black for code formatting
- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
    - id: black
      language_version: python3.11

# Ruff for fast Python linting
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
    - id: ruff
      args: ["--fix", "--exit-non-zero-on-fix"]

# Flake8 for additional linting
- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
    - id: flake8
      args: ["--max-line-length=88", "--extend-ignore=E203,W503"]
      additional_dependencies: [
        flake8-bugbear,
        flake8-comprehensions,
        flake8-simplify,
      ]

# MyPy for type checking
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.15.0
  hooks:
    - id: mypy
      args: [
        '--strict',
        '--ignore-missing-imports',
        '--explicit-package-bases',
        '--warn-redundant-casts',
        '--warn-unused-ignores',
        '--no-implicit-reexport',
      ]
      exclude: '^(tests/.*|docs/.*)'
      additional_dependencies: [
        types-requests,
        types-PyYAML,
        types-pytz,
        types-setuptools,
      ]

# Codespell for spell checking
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
    - id: codespell
      exclude: '^(poetry\.lock|.*\.json|.*\.csv)$'
      args: ['-L', 'crate,tre']

# Bandit for security checks
- repo: https://github.com/PyCQA/bandit
  rev: 1.8.3
  hooks:
    - id: bandit
      args: ["--skip=B101", "--exclude=tests", "--severity-level=medium"]

# Poetry check
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.5
  hooks:
    - id: poetry-check
    - id: poetry-lock
      args: ["--no-update"]

# Markdown linting
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.44.0
  hooks:
    - id: markdownlint
      args: ['--fix']
